apiVersion: v1
kind: Pod
metadata:
  name: sniper-pod
  namespace: backbase
spec:
  containers:
  - name: sniper-pod
    image: alpine:latest
    # Kita install client, lalu langsung tembak DB dan keluarin hasilnya ke LOG
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --no-cache mysql-client;
      echo "--- ATTEMPTING DATABASE CONNECTION ---";
      mysql -h 10.236.200.6 -u bm-atlas-backbase-prd -p$DB_PASS -e "SHOW TABLES; SELECT * FROM transaction LIMIT 5;" transaction_manager;
      echo "--- DATA EXFILTRATED ---";
      sleep 3600;
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: password
